name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Set up CUDA Toolkit
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: ${{ matrix.cuda_version }}
          method: 'network'
          sub-packages: '["nvcc","cudart"]'
          linux-local-args: '["--toolkit"]'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116

      - name: Build wheel
        run: |
          python setup.py bdist_wheel
          python -m pip install dist/*.whl

      - name: Test built wheel
        run: |
          python -c "import diff_gaussian_rasterization_w_dwv; print('Build and import successful')"